package com.accenture.shared;

public enum TypeVehicule {
    CITADINE,
    BERLINE,
    SUV,
    FAMILIALE,
    VOITURE_ELECTRIQUE,
    VOITURE_DE_LUXE,
    LIMOUSINE,
    FOURGON,
    PICK_UP,
    CAMION_BENNE,
    DEPANNEUSE,
    CAMION_NACELLE,
    CAMPING_CAR_PROFILE,
    CAMPING_CAR_INTEGRAL,
    CAMPING_CAR_CAPUCINE,
    CAMPING_CAR_FOURGON,
    CAMPING_CAR_VAN,
    VELO
}
